axis_linear_x: 1  # Left thumb stick vertical
axis_linear_y: 0
scale_linear: 0.7
scale_linear_turbo: 1.0

axis_angular: 3  # Left thumb stick horizontal
scale_angular: 0.4
scale_angular_turbo: 6.0

enable_omnidireccional: 1
enable_turbo: -1

enable_button: 2  # Left trigger button
enable_omnidireccional_button: 5 # Right trigger button
enable_turbo_button: 1  # Right trigger button